[workspace]
members = [
    "mp4parse",
    "mp4parse_capi",
    "mp4parse_fallible"
]

# Somewhat heavy-handed, but we want at least -Z force-overflow-checks=on.
[profile.release]
debug-assertions = true

